# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder_app', '0003_form_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='publishedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
