# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder_app', '0004_auto_20170829_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonSubmission', models.TextField()),
                ('publishedDate', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formbuilder_app.Form')),
            ],
        ),
    ]
